export const SUPERUSER_CHECK_REQUEST = 'SUPERUSER_CHECK_REQUEST';
export const SUPERUSER_CHECK_SUCCESS = 'SUPERUSER_CHECK_SUCCESS';
export const SUPERUSER_CHECK_FAIL = 'SUPERUSER_CHECK_FAIL';

export const SUPERUSER_CREATE_REQUEST = 'SUPERUSER_CREATE_REQUEST';
export const SUPERUSER_CREATE_SUCCESS = 'SUPERUSER_CREATE_SUCCESS';
export const SUPERUSER_CREATE_FAIL = 'SUPERUSER_CREATE_FAIL';

export const SUPERUSER_SIGNIN_REQUEST = 'SUPERUSER_SIGNIN_REQUEST';
export const SUPERUSER_SIGNIN_SUCCESS = 'SUPERUSER_SIGNIN_SUCCESS';
export const SUPERUSER_SIGNIN_FAIL = 'SUPERUSER_SIGNIN_FAIL';
